### PR TITLE
Update of Es-es Translate

### PR DESCRIPTION
**Pull request by helldark**
only one archive an this is localization.json, tomorrow i continue with the rest

### CODE REVIEW

**Comment by helldark** [comment]
only one archive an this is localization.json, tomorrow i continue with the rest

**Comment by pipliz** [comment]
I'll wait for the rest :)

**Comment by helldark** [comment]
I finished!!! :DDDD

**Comment by helldark** [comment]
is my idea or the accent mark is bugged in this system?

**Comment by helldark** [comment]
i forgot to mention that, i don't have the game, my friend request me complete the translate, when you update the translation, i go to their home (my friend he has the game) to see if there is any issue, in special with the accent mark like i mentioned earlier in the comments.

**Comment by pipliz** [comment]
Merged it manually, had to convert from ansi to utf-8 for it to work :)

**Pull request closed without merging**
