### PR TITLE
Update ru-RU locale

### PR DESCRIPTION
**Pull request by Oleg720**

### CODE REVIEW

**Comment by Oleg720** [comment]
Why did not you take Pull request?

**Comment by pipliz** [comment]
I'll accept it later, no worries. Sort of waiting on your step 2 of ~2 here.

**Comment by Oleg720** [comment]
Okay. I just did not understand what the word "Bloomery" means?

**Comment by pipliz** [comment]
https://en.wikipedia.org/wiki/Bloomery

**Pull request merged**
